MorphoSource/MorphoSource_SF

- Gemfile
- Gemfile.lock
- config/database.yml
- config/fedora.yml
- config/solr.yml
@JuliaWinchester @simonmchoy We can use this in our PostgreSQL/MySQL conversation.
> Database config and Gemfile updated to use postgresql in production.

- Gemfile
@JocelynTriplett @simonmchoy Don't merge this PR yet -- I want to test deploying it to the dev server first.
> Use puma instead of passenger in production.

- .gitlab-ci.yml
This is a step stone to a more flexible automated deployment.
> Initial version of GitLab CI/CD config

- app/actors/hyrax/actors/media_actor.rb
- app/assets/javascripts/hyrax/ms_media_form.js
- app/assets/javascripts/hyrax/ms_physical_objects_form.js
- app/forms/hyrax/media_form.rb
- app/models/concerns/morphosource/media_metadata.rb
- Added scale_bar_units and scale_bar fields to Photogrammetry
- Added methods to MediaActor that concatenate scale bar target type, distance, and units into scale bar field.
> MR-216: Media updates - additional metadata fields

- Gemfile
- Gemfile.lock
[Xray-rails](https://github.com/brentd/xray-rails) is a development tool that was shown to Julie and me by DCE during Samvera Camp. It shows which files are responsible for different sections of the UI.
> Add Xray-rails 

- app/actors/hyrax/actors/attachment_actor.rb
- app/controllers/hyrax/attachments_controller.rb
- app/forms/hyrax/attachment_form.rb
- app/indexers/attachment_indexer.rb
- app/models/attachment.rb
- app/presenters/hyrax/attachment_presenter.rb
- app/views/hyrax/attachments/_attachment.html.erb
- config/initializers/hyrax.rb
- config/locales/attachment.de.yml
- config/locales/attachment.en.yml
- config/locales/attachment.es.yml
- config/locales/attachment.fr.yml
- config/locales/attachment.it.yml
- config/locales/attachment.pt-BR.yml
- config/locales/attachment.zh.yml
- spec/actors/hyrax/actors/attachment_actor_spec.rb
- spec/controllers/hyrax/attachments_controller_spec.rb
- spec/forms/hyrax/attachment_form_spec.rb
- spec/models/attachment_spec.rb
- spec/presenters/hyrax/attachment_presenter_spec.rb
This pull request creates an Attachment work, which will be used for metadata-field file attachments in future stories
> Create attachment work [Addresses MR-271]

- app/actors/hyrax/actors/add_to_work_actor.rb
- app/assets/javascripts/application.js
- app/forms/hyrax/attachment_form.rb
- app/forms/hyrax/biological_specimen_form.rb
- app/forms/hyrax/cultural_heritage_object_form.rb
- app/forms/hyrax/device_form.rb
- app/forms/hyrax/institution_form.rb
- app/forms/hyrax/media_form.rb
- app/forms/hyrax/processing_event_form.rb
- app/forms/morphosource/form_methods.rb
- app/views/hyrax/base/_form_parent_work_relationships.html.erb
- app/views/hyrax/base/_form_relationships.html.erb
- config/locales/hyrax.en.yml
- lib/assets/javascripts/morphosource/add_parent.js
- lib/assets/javascripts/morphosource/editor.es6
- lib/morphosource/works/base.rb
- spec/actors/hyrax/actors/add_to_works_actor_spec.rb
- Adding parents to work show view coming on a separate PR.
> MR-243 Add a work to its parent work from the edit form

- app/models/solr_document.rb
- app/presenters/hyrax/attachment_presenter.rb
- app/presenters/hyrax/biological_specimen_presenter.rb
- app/presenters/hyrax/cultural_heritage_object_presenter.rb
- app/presenters/hyrax/device_presenter.rb
- app/presenters/hyrax/imaging_event_presenter.rb
- app/presenters/hyrax/institution_presenter.rb
- app/presenters/hyrax/media_presenter.rb
- app/presenters/hyrax/processing_event_presenter.rb
- app/presenters/morphosource/presenter_methods.rb
- app/views/hyrax/base/_parents.html.erb
- app/views/hyrax/base/show.html.erb
- spec/presenters/morphosource/presenter_methods_spec.rb
- spec/views/morphosource/show_parents_spec.rb
- Shows parents under relationships and in a section similar to items. 
- Adds PresenterMethods module that will need to be included on all work presenter files.
> MR-243 - Display parents on work show view

- app/controllers/hyrax/file_sets_controller.rb
- config/initializers/morphosource.rb
overriding the method FileSetPresenter with MsFileSetPresenter in either application.rb or morphosource.rb is not working intermittently, where the method get reset back to FileSetPresenter.  So I had to revert back to overriding in the controller instead.
> override show_presenter in controller 

- app/indexers/attachment_indexer.rb
- app/indexers/biological_specimen_indexer.rb
- app/indexers/cultural_heritage_object_indexer.rb
- app/indexers/device_indexer.rb
- app/indexers/imaging_event_indexer.rb
- app/indexers/institution_indexer.rb
- app/indexers/media_indexer.rb
- app/indexers/morphosource/work_indexer.rb
- app/indexers/processing_event_indexer.rb
- app/models/solr_document.rb
- spec/support/shared_examples_for_morphosource_works.rb
Sortable title is the work's "first" title.
> Add index field to permit sorting works by title.

- app/controllers/submissions_controller.rb
- app/models/submission.rb
- spec/models/submission_spec.rb
Also refactors the step name out into a constant so the string literal doesn't
have to be used everywhere.
> Validate that institution is selected on institution page; MR-318.

- app/views/hyrax/base/_form_progress.html.erb
- config/locales/morphosource.en.yml
- lib/assets/javascripts/morphosource/media/upload_formats.js.erb
- lib/assets/javascripts/morphosource/ms_save_work_control.es6
Refactored so that save_work_control is able to check if the upload_formats requirement can be checked on initial page load.
> MR-355: Enable the save button when loading a media work for editing

- spec/actors/hyrax/actors/attachment_actor_spec.rb
- spec/actors/hyrax/actors/device_actor_spec.rb
- spec/actors/hyrax/actors/imaging_event_actor_spec.rb
- spec/actors/hyrax/actors/institution_actor_spec.rb
- spec/actors/hyrax/actors/processing_event_actor_spec.rb
- spec/controllers/hyrax/imaging_events_controller_spec.rb
- spec/forms/hyrax/imaging_event_form_spec.rb
- spec/models/collection_spec.rb
- spec/models/file_set_spec.rb
- spec/models/qa/local_authority_entry_spec.rb
- spec/models/qa/local_authority_spec.rb
- spec/presenters/hyrax/attachment_presenter_spec.rb
Deletes files that are empty except for test placeholders.
> Remove Empty Tests

- app/controllers/hyrax/media_controller.rb
- app/views/hyrax/media/_attribute_rows.html.erb
Works in my testing on Chrome and Firefox. May need additional testing for dev.
> MR-473: fix download button

- app/assets/javascripts/submission.js
- app/assets/stylesheets/morphosource/submission_flow.scss
- app/controllers/submissions_controller.rb
- app/helpers/morphosource_helper.rb
- app/models/ability.rb
- app/models/submission.rb
- app/views/submissions/_taxonomy_create.html.erb
- app/views/submissions/_taxonomy_form.html.erb
- app/views/submissions/_taxonomy_select.html.erb
- app/views/submissions/show.html.erb
- app/views/submissions/taxonomy.html.erb
- config/locales/submission.en.yml
- config/routes.rb
- spec/controllers/submissions_controller_spec.rb
- spec/helpers/morphosource_helper_spec.rb
- spec/models/ability_spec.rb
When creating a new BSO, users can select an existing taxonomy to associate with the specimen or create a new one.
> MR-461 & MR-462: Adds taxonomies to multi-work submission

- db/schema.rb
Results of running rails db:migrate
> Update DB Schema

- app/actors/hyrax/actors/biological_specimen_actor.rb
- app/actors/hyrax/actors/media_actor.rb
- app/controllers/catalog_controller.rb
- app/forms/hyrax/media_form.rb
- app/models/biological_specimen.rb
- app/models/concerns/morphosource/media_metadata.rb
- app/models/solr_document.rb
- app/presenters/hyrax/media_presenter.rb
- app/views/hyrax/media/_attribute_rows.html.erb
- app/views/hyrax/media/_showcase_file_object_details.html.erb
- lib/ms1to2/models/biological_specimen.rb
- lib/ms1to2/models/media.rb
- spec/actors/hyrax/actors/media_actor_spec.rb
- spec/forms/hyrax/media_form_spec.rb
> Updated media titles, IDs now part of titles where possible, minor ms1to2 updates

- app/helpers/hyrax/taxonomy_helper.rb
- app/presenters/hyrax/media_presenter.rb
- app/views/hyrax/media/_showcase_file_object_details.html.erb
- spec/renderers/hyrax/renderers/showcase_taxonomy_renderer_spec.rb
Changes:
set mime type properly, handle non stack images
added full description, labels in file objects
updated tests for taxonomy
> Media show page 4

- lib/tasks/morphosource.rake
To run these rake tasks and output the info to console (and not just to the server log), run:
rails morphosource:to_stdout morphosource:check_derivatives
rails morphosource:to_stdout morphosource:check_file_ingests
> Added rake tasks to check derivatives and file binary ingests

- app/views/hyrax/media/_showcase_show_actions.html.erb
Reverts to previous version of showcase actions partial for now.
> fixes error caused by nil fileset_accessibility

- spec/spec_helper.rb
Previous change worked fine for Travis, but not when running tests locally. This should work for both.
> Selenium not able to find Firefox in local development environment

- app/models/media.rb
- app/views/hyrax/base/_form_parent_work_relationships.html.erb
> MR-576: show parent details on Media work edit page

- app/controllers/morphosource/my/cart_items_controller.rb
- app/controllers/morphosource/my/downloads_controller.rb
- app/controllers/morphosource/my/request_managers_controller.rb
- app/controllers/morphosource/my/requests_controller.rb
- app/helpers/morphosource/cart_item_helper.rb
- app/models/cart_item.rb
- app/models/media_cart.rb
- app/models/user.rb
- app/views/morphosource/my/cart/_list_restricted_items.html.erb
- db/migrate/20190211161448_create_media_carts.rb
- db/migrate/20190916183751_drop_table_media_cart.rb
- db/migrate/20190916185140_remove_media_cart_references.rb
- db/migrate/20190917142759_change_cart_item_note_to_use.rb
- db/schema.rb
- lib/morphosource/my/cart_items_behavior.rb
- spec/controllers/morphosource/my/cart_items_controller_spec.rb
- spec/controllers/morphosource/my/downloads_controller_spec.rb
- spec/controllers/morphosource/my/request_managers_controller_spec.rb
- spec/controllers/morphosource/my/requests_controller_spec.rb
- spec/helpers/morphosource/cart_item_helper_spec.rb
- spec/models/cart_item_spec.rb
- spec/models/user_spec.rb
- spec/support/cart_items/shared_context_for_cart_items.rb
Also changes name of cart item intended use column & edits parameter name for mark_as method.
> MR-573: Refactor to remove media cart model

- app/controllers/hyrax/biological_specimens_controller.rb
this change is an attempt to fix the issue in https://duldev.atlassian.net/browse/MR-593
> Fix for MR-593 undefined method model_name on BSO edit page 

- lib/morphosource/works/base.rb
Fixes bug causing reindexing of members.
> edit descendants method

- .travis.yml
- app/actors/hyrax/actors/collections_membership_actor.rb
- app/forms/hyrax/device_form.rb
- app/models/concerns/morphosource/device_metadata.rb
- app/models/solr_document.rb
- app/presenters/hyrax/device_presenter.rb
- app/presenters/hyrax/media_presenter.rb
- app/views/hyrax/devices/_attribute_rows.html.erb
- app/views/hyrax/media/_member_edit.html.erb
- app/views/hyrax/media/_parent_imaging_event.html.erb
- app/views/records/edit_fields/_slice_thickness.html.erb
- config/initializers/hyrax.rb
- lib/hyrax/configuration.rb
- lib/morphosource/configurable.rb
- lib/ms1to2/models/device.rb
- lib/tasks/morphosource.rake
- spec/controllers/submissions_controller_spec.rb
- spec/features/accessibility/demo_bso_showcase_spec.rb
- spec/features/accessibility/demo_media_showcase_spec.rb
- spec/forms/hyrax/device_form_spec.rb
- spec/models/device_spec.rb
- spec/models/solr_document_spec.rb
- spec/presenters/hyrax/device_presenter_spec.rb
- spec/services/morphosource/i_dig_bio_search_service_spec.rb
- spec/spec_helper.rb
- spec/vcr_helper.rb
- spec/views/hyrax/devices/_attribute_row.html.erb_spec.rb
Bug fixes for MR-691, 696, 659, 653, 596, 506, 498, 646
> Bug fixes, Feb 2020

- app/views/hyrax/media/_showcase_image_acquisition_details.html.erb
Fixes the typos "MophoSource" for "MorphoSource"
> Correct two typos in _showcase_image_acquisition_details.html.erb

- .travis.yml
- spec/lib/morphosource/derivatives/blender_spec.rb
- spec/lib/morphosource/derivatives/gltf_pipeline_spec.rb
- spec/lib/morphosource/derivatives/processors/ct_image_series_spec.rb
- spec/lib/morphosource/derivatives/processors/mesh_spec.rb
- spec/lib/morphosource/derivatives_spec.rb
- vendor/blender_config/scripts/blender_characterize_mesh.py
- vendor/blender_config/scripts/blender_derive_mesh.py
Update Blender 2.7.9 to 2.8.2 (MR-715)
> Blender2.8.2
