- Gemfile
- Gemfile.lock
- Updated Gemfile structure (moved gems that apply to all environments to the top; combined multiple "development,test" groups into one, removed some default comments to streamline)
- Installed additional gems:
gem 'rspec-its'
gem 'rails-controller-testing'
gem 'factory_bot_rails', '~> 4.8'
gem 'webmock'
> MR-170: Add additional testing gems

- config/environments/production.rb
This is to get Hyrax notifications to work behind Apache reverse proxy
> Set config.action_cable.allowed_request_origins when ENV["HOST_NAME"]

- config/environments/production.rb
Otherwise log/production.log just keeps growing.
> Configure log rotation in production environment

- db/migrate/20180727212032_add_badge_color_to_collection_types.rb
- db/schema.rb
- Adds missing badge_color field to collection types; can't create new collections without this change. 
- See [rdr upgrade to 2.1.0](https://github.com/duke-libraries/rdr/blob/05a4b3717391b78b301aebb19dbcbca5737614e7/db/migrate/20180601173338_add_badge_color_to_collection_types.hyrax.rb)
> Add badge color to collection types

- app/assets/javascripts/hyrax/ms_media_form.js
- app/assets/javascripts/hyrax/ms_physical_objects_form.js
- app/forms/hyrax/media_form.rb
- app/forms/hyrax/physical_object_form.rb
- app/models/concerns/morphosource/media_metadata.rb
Adding single-value fields to physical object works prevented media works from recognizing the title field on save. Adding single-value fields to media works fixes this problem.
> Fix for Saving Media Works

- app/assets/javascripts/hyrax/ms_media_form.js
- app/assets/javascripts/hyrax/ms_physical_objects_form.js
- app/views/records/edit_fields/_title.html.erb
- Discovered that the title partial had a 'hide' class on it, which had been messing with its appearance on the work form. Fixed the partial and removed code from javascripts that is no longer needed.
> Fix partial that was hiding title fields

- Gemfile
- Gemfile.lock
- app/assets/javascripts/hyrax/ms_media_form.js
- app/views/records/edit_fields/_scale_bar.html.erb
- Xray-rails was messing with the show/hide functions on the work form, so I took it out for now. 
- Put the logic for clearing the scale bar inputs in the scale bar field javascript, so they are available to a user while editing even if they switch media types, and only are cleared if the media type is not photogrammetry on submit.
> Scale bar Fix

- config/environments/production.rb
Enable public file server is a requirement for using UV in production environments (i.e., https://github.com/samvera/hyrax/issues/2326). This commit enables the public file server for production.
> Enable public file server for UV in production environment

- app/helpers/morphosource_helper.rb
- spec/helpers/morphosource_helper_spec.rb
Accounts for the fact that sometimes we need the class names and sometimes
(e.g., for display) we want the human readable form.
Also sorts the list so they're in a consistent and predictable order.
> Refactor lineage types helpers.

- .gitignore
- app/assets/javascripts/hyrax/ga_events.js
- app/views/_ga.html.erb
- config/analytics.yml
- config/initializers/hyrax.rb
- config/initializers/legato.rb
- Captures usage and download statistics that can be viewed through the MorphoSource Google Analytics account.
- Displays usage in the UI
- Creates separate tracking IDs for development, preproduction, and production. 
- Instructions to set up for your development environment to follow.
> MR-172: Google Analytics API integration and configuration

- app/views/hyrax/base/_form_relationships.html.erb
- app/views/hyrax/base/_form_uploads_list.html.erb
- lib/assets/javascripts/morphosource/media/upload_formats.js
- The first commit adds a partial containing a hidden list of previously uploaded file names so they can be taken into account if the user changes the Media Type of the work. 
- The second commit is for format improvements - converts snake case to more conventional camel case and uses semicolons more consistently.
> MR-327 - include previously uploaded files when evaluating format requirement

- app/views/hyrax/base/_form_relationships.html.erb
- app/views/hyrax/base/_form_uploads_list.html.erb
- lib/assets/javascripts/morphosource/media/upload_formats.js.erb
Hyrax lists previously uploaded files in the 'representative media' section of the edit form, so it wasn't necessary for me to add a partial. 
Also sneaking in a small change to update the accepted formats message on the files tab when the page loads for the edit form.
> MR-346: Refactor getting file names for previous uploads

- app/actors/hyrax/actors/file_set_actor.rb
- app/assets/javascripts/application.js
- app/controllers/hyrax/media_controller.rb
- app/forms/morphosource/form_methods.rb
- app/indexers/media_indexer.rb
- app/models/concerns/morphosource/media_metadata.rb
- app/models/media.rb
- app/models/solr_document.rb
- app/views/hyrax/base/_file_set_visibility.html.erb
- app/views/hyrax/base/_form_visibility_component.html.erb
- app/views/hyrax/my/works/_default_group.html.erb
- app/views/hyrax/my/works/_list_works.html.erb
- config/locales/morphosource.en.yml
- lib/assets/javascripts/morphosource/media/file_set_visibility.js.erb
- spec/actors/hyrax/actors/file_set_actor_spec.rb
- spec/controllers/hyrax/media_controller_spec.rb
- spec/models/media_spec.rb
- spec/rails_helper.rb
- Can assign attached file visibility to be either the same as the work or private.
- Displays associated file visibilities for each work on the dashboard work list.
> MR-351: Assign File Set Visibility from the Media Work form

- Gemfile.lock
- app/views/hyrax/base/_representative_media.html.erb
This commit enables preview viewing of DRACO-compressed GLTF 3D meshes using the Universal Viewer, along with changes to the Ruby gem pul_uv_rails and the Javascript packages universalviewer and virtex3d. Most of the changes to enable this functionality are in these secondary packages, and are described below:
[virtex3d](https://github.com/edsilv/virtex): Virtex is the framework used by UV to view 3D media, using three.js. Changes made include connecting a DRACO loader instance to the GLTF loader instance and creating an optional initialization flag to set a DRACO decoder file location. Also, a distribution version of virtex was produced incorporating these changes as well as appropriate loader and decoder files from Three.js. The changes required for this can be seen in my [virtex …
> Enable viewing of DRACO-compressed GLTF 3D meshes

- lib/assets/javascripts/morphosource/ms_save_work_control.es6
When editing a media work that has previously added files but no new files added, the formats requirement is prevented from being unchecked when media type changes. This change checks the requirement only once during page setup instead of multiple times.
> MR-411: Changing the media type doesn't uncheck the format requirement

- config/environments/development.rb
Related to #110, this should fix having to restart the server to see changes inside the Vagrant environment. From @simonmchoy in Slack.
https://gist.github.com/stungeye/3d7488affff083365bfd6bfffb7eec14
> Use ActiveSupport::FileUpdateChecker in dev environment for Vagrant shared folder compatibility

- app/controllers/application_controller.rb
- app/controllers/morphosource/my/cart_items_controller.rb
- app/models/cart_item.rb
- app/models/media_cart.rb
- app/models/user.rb
- app/presenters/morphosource/presenter_methods.rb
- app/search_builders/morphosource/my/cart_items/cart_items_search_builder.rb
- app/search_builders/morphosource/my/cart_items/downloads_search_builder.rb
- app/views/_user_util_links.html.erb
- app/views/hyrax/base/show.html.erb
- app/views/hyrax/dashboard/_sidebar.html.erb
- app/views/hyrax/dashboard/sidebar/_downloads.html.erb
- app/views/morphosource/my/_document_list.html.erb
- app/views/morphosource/my/_scripts.js.erb
- app/views/morphosource/my/cart_items/_default_group.html.erb
- app/views/morphosource/my/cart_items/_list_works.html.erb
- app/views/morphosource/my/cart_items/_results_pagination.html.erb
- app/views/morphosource/my/cart_items/index.html.erb
- config/locales/morphosource.en.yml
- config/routes.rb
- db/migrate/20190211161448_create_media_carts.rb
- db/migrate/20190211161505_create_cart_items.rb
- db/schema.rb
- spec/controllers/morphosource/my/cart_items_controller_spec.rb
- spec/models/user_spec.rb
**To add a media cart to all current users on your machine, run 'User.all.each{|u| u.create_user_media_cart}' in the console.**
- Automatically creates a media cart object for each new user.
- Adds a 'Downloads' section to the dashboard which includes the media cart and previous downloads. 
- Adds a media cart icon to the top right corner for signed-in users.
- Adds a 'Add to Cart' button to work show view for signed-in users.
- 'Add to Cart' button changes to 'Already in Cart' and links to the media cart if the work has already been added to the cart.
- The media cart displays the works that have been added to the cart.
- The previous downloads section displays works that the user has downloaded (not yet implemented, but can try it out by changing a cartItem downloaded property to false) …
> MR-404: Creates a Media Cart container for media works

- app/controllers/morphosource/my/cart_items_controller.rb
- app/views/morphosource/my/cart_items/index.html.erb
- config/routes.rb
- spec/controllers/morphosource/my/cart_items_controller_spec.rb
I discovered a couple of bugs when there are more than 10 items added to the media cart or downloads pages. The page links at the bottom of the media cart page were linking to the downloads page, and the item counts were only counting items on the page instead of total items. This PR resolves both issues.
> MR-418: fix item count and pagination links for media cart and downloads

- Gemfile
- Gemfile.lock
- app/controllers/hyrax/file_sets_controller.rb
- app/controllers/hyrax/media_controller.rb
- app/models/ability.rb
- app/views/hyrax/media/_attribute_rows.html.erb
- config/routes.rb
- spec/controllers/hyrax/media_controller_spec.rb
- spec/routing/zip_routing_spec.rb
MR-405: This adds a `zip` method to `MediaController` which takes one or more `Media` ID's in an array parameter named `ids` and streams a zip of all related `FileSet`s using the `zipline` gem.
This adds a downstream dependency on `libcurl4-openssl-dev`, added to `morphosource-vagrant` here: https://github.com/MorphoSource/morphosource-vagrant/commit/b2b292d9700783aad6c774d6a62a1761f1a2f429
MR-394: Added a link on the Media show page to download all FileSets with a single button using the above zip functionality: https://github.com/MorphoSource/MorphoSource_SF/commit/aa0df15fbcea2339f7ac0f0077f44f837c4ce958
> MR-405: zip functionality, & MR-394: media download

- app/models/ability.rb
- app/models/concerns/morphosource/ability.rb
- config/initializers/hyrax.rb
A better way to do this would probably be if we could just set `cannot [ :download: ], FileSet`, but it seems like Hyrax/CanCanCan uses special logic for determining download permissions. By overriding the `download_users`/`download_groups` methods to always return an empty set, we can completely disable FileSet downloads.
> MR-393: disable FileSet downloads

- app/controllers/morphosource/my/cart_items_controller.rb
- app/models/cart_item.rb
- app/models/user.rb
- app/views/hyrax/base/show.html.erb
- app/views/morphosource/batch_edits/_copy_selected.html.erb
- app/views/morphosource/batch_edits/_download_all.html.erb
- app/views/morphosource/batch_edits/_download_selected.html.erb
- app/views/morphosource/batch_edits/_remove_selected.html.erb
- app/views/morphosource/batch_select/_add_button.html.erb
- app/views/morphosource/my/_batch_edits_actions.html.erb
- app/views/morphosource/my/_document_list.html.erb
- app/views/morphosource/my/_scripts.js.erb
- app/views/morphosource/my/cart_items/_batch_actions.html.erb
- app/views/morphosource/my/cart_items/_default_group.html.erb
- app/views/morphosource/my/cart_items/_list_works.html.erb
- app/views/morphosource/my/cart_items/_results_pagination.html.erb
- app/views/morphosource/my/cart_items/index.html.erb
- config/locales/morphosource.en.yml
- config/routes.rb
- db/migrate/20190220151203_add_date_downloaded_to_cart_items.rb
- db/migrate/20190301152534_add_in_cart_to_cart_items.rb
- db/migrate/20190306225507_remove_downloaded_from_cart_items.rb
- db/schema.rb
- spec/controllers/morphosource/my/cart_items_controller_spec.rb
- spec/models/user_spec.rb
- spec/routing/cart_items_routing_spec.rb
- Uses media/#zip to create zip files for works represented by media cart items.
- Can download one, multiple, or all works in the media cart.
- the Previous Downloads page provides a list of works downloaded by the user.
- Works can be copied from the previously downloaded page to the media cart to be downloaded again.
- Users can delete one, multiple, or all items in their media cart.
> MR-133, MR-406 - Download Zipped Files from the Media Cart

- config/authorities/modalities.yml
This probably needs to be updated on <https://www.idigbio.org/wiki/index.php/3D_Scan_Modality_Subtypes> as well - not sure if there's a more involved process there, but probably good to fix this before it goes "live".
> "Synchotron" should instead be "Synchrotron"

- app/models/biological_specimen.rb
- app/models/cultural_heritage_object.rb
- app/models/media.rb
- spec/controllers/morphosource/my/cart_items_controller_spec.rb
- spec/presenters/hyrax/media_presenter_spec.rb
We can't access the id from the Hyrax actor context, because the ID isn't generated until after the object is saved in Fedora. By using the `after_create` callback chain instead, we can update the title to prefix the title with the generated id only when the object is first created (after it's been saved in Fedora so that the id is present).
> MR-449: update title formulas for Media, BSO, and CHO

- app/actors/hyrax/actors/imaging_event_actor.rb
- app/actors/hyrax/actors/processing_event_actor.rb
- app/models/imaging_event.rb
- app/models/processing_event.rb
- spec/presenters/hyrax/imaging_event_presenter_spec.rb
As noted on the ticket, these can have other parent work types that weren't specified to be in the title. The code paths for adding these to the titles have been left commented out.
> MR-448: Auto-generate titles for Imaging/Processing Events

- app/models/biological_specimen.rb
- app/models/cultural_heritage_object.rb
- app/models/imaging_event.rb
- app/models/media.rb
- app/models/processing_event.rb
Related to e.g. [MR-448](https://github.com/MorphoSource/MorphoSource_SF/pull/128), this switches title generation to use `after_save` instead of `after_create` so the title prefix doesn't get lost on updates.
> Change after_create :add_id_to_title to use after_save instead

- app/controllers/catalog_controller.rb
- app/forms/hyrax/processing_event_form.rb
- app/models/concerns/morphosource/processing_event_metadata.rb
- app/models/solr_document.rb
- app/presenters/hyrax/processing_event_presenter.rb
- app/services/morphosource/processing_activity_types_service.rb
- app/views/hyrax/processing_events/_attribute_rows.html.erb
- app/views/records/edit_fields/_processing_activity.html.erb
- app/views/records/edit_fields/_processing_activity_description.html.erb
- app/views/records/edit_fields/_processing_activity_software.html.erb
- app/views/records/edit_fields/_processing_activity_type.html.erb
- config/authorities/processing_activity_types.yml
- spec/forms/hyrax/processing_event_form_spec.rb
The concatenated repeatable multi-field processing_activity needs to be created. This multi-field is a concatenated set of three individual metadata fields: processing_activity_type (drop-down), processing_activity_software (single line text entry), processing_activity_description (multi-line text entry).
> MR-457: add a processing_activity field to Processing Events

- app/presenters/hyrax/biological_specimen_presenter.rb
- app/renderers/hyrax/renderers/related_taxonomies_renderer.rb
- app/renderers/hyrax/renderers/showcase_taxonomy_renderer.rb
- app/views/hyrax/biological_specimens/_attribute_rows.html.erb
- app/views/hyrax/biological_specimens/_showcase_taxonomy.html.erb
- lib/morphosource/configurable.rb
- spec/renderers/hyrax/renderers/related_taxonomies_renderer_spec.rb
- spec/renderers/hyrax/renderers/showcase_taxonomy_renderer_spec.rb
the labels constant in the configurable file seemed to be loading before the translation files, so the labels often say 'translation unavailable' instead of the real label. This change calls the translation directly.
> MR-494: fix missing translations for labels

- Gemfile
- Gemfile.lock
- lib/morphosource/works/mime_types.rb
- limits file sets to direct children (will not show file sets belonging to child media works)
- limits number of file sets by media type:
- Image/Video: all file sets
- Mesh: one file set
- Other/Photogrammetry: no file sets
- CT/MRI - coming soon
> MR-503: Limit which file sets are included in a media work's manifest

- app/views/hyrax/media/_showcase_image_acquisition_details.html.erb
Prevents errors being thrown if a media work is created through the dashboard.
New if/end on lines 38 and 44.
> Only show imaging event metadata if there is an imaging event

- .travis.yml
Running `bundle install` currently takes about 4 minutes of each Travis build. Caching this should hopefully speed things up.
> Add "cache: bundler" to Travis config

- app/controllers/morphosource/my/cart_items_controller.rb
- app/controllers/morphosource/my/downloads_controller.rb
- app/controllers/morphosource/my/media_carts_controller.rb
- app/controllers/morphosource/my/requests_controller.rb
- app/helpers/morphosource/cart_item_helper.rb
- app/models/cart_item.rb
- app/models/media.rb
- app/models/user.rb
- app/presenters/hyrax/media_presenter.rb
- app/views/hyrax/media/_showcase_show_actions.html.erb
- config/routes.rb
- lib/morphosource/my/cart_items_behavior.rb
- spec/controllers/morphosource/my/cart_items_controller_spec.rb
- spec/controllers/morphosource/my/downloads_controller_spec.rb
- spec/controllers/morphosource/my/requests_controller_spec.rb
- spec/helpers/morphosource/cart_item_helper_spec.rb
- spec/models/media_spec.rb
- spec/models/user_spec.rb
- spec/routing/cart_items_routing_spec.rb
Modifies behavior for the three buttons at the top of the Media Showcase page:
* Download/Request Download/Download Requested 
* Add to Cart/Item in Cart
* Edit
Adds:
* Download Unavailable
Download button:
Appears when:
- Media publication status is "open" or
- Viewer has edit privileges for the Media or
- Media publication status is "restricted", the user has requested download, and their request status is "Approved"
What it does: 
- downloads the item.
Request Download button:
Appears when:
- Media publication status is "restricted"
What it does:
- If a user has already added the Media to their cart, that cart item is located and requested. If the user has not already added it to their cart, a new item is created, added to their cart, and requested. 
Download Requested (disabled): …
> MR-566: Update showcase media buttons

- .travis.yml
Switching from `curl` to `wget` without quiet mode should also stop Travis from considering a slow download a failed build due to no output within the timeout period.
> Try caching blender download for Travis

- app/helpers/morphosource_helper.rb
- app/models/media.rb
- app/presenters/morphosource/publication_badge.rb
- app/views/hyrax/my/works/_default_group.html.erb
- app/views/hyrax/my/works/_list_works.html.erb
- config/locales/morphosource.en.yml
- spec/helpers/morphosource_helper_spec.rb
- spec/models/media_spec.rb
Replaces 'visibility' and 'file visibility' columns with 'publication status'. For Media works, displays custom publication statuses (open, restricted, preview, hidden, embargo, lease); for non-Media works, displays normal Hyrax visibility.
> MR-571: Add publication status to works page

- app/controllers/morphosource/my/cart_items_controller.rb
- app/controllers/morphosource/my/media_carts_controller.rb
- app/controllers/morphosource/my/requests_controller.rb
- app/helpers/morphosource/cart_item_helper.rb
- app/models/cart_item.rb
- app/views/morphosource/my/modals/request/_showcase_body.html.erb
- config/routes.rb
- lib/morphosource/my/cart_items_behavior.rb
- spec/controllers/morphosource/my/cart_items_controller_spec.rb
- spec/controllers/morphosource/my/media_carts_controller_spec.rb
- spec/controllers/morphosource/my/requests_controller_spec.rb
- spec/helpers/morphosource/cart_item_helper_spec.rb
When a user downloads a work from the media showcase page, checks to see if the user already has an undownloaded item is in the cart or if there is an undownloaded active request for the work. If it finds one, it marks the item as downloaded. If it can't find one, it creates a new cart item and marks it as downloaded.
> MR-579: Downloading a media work from the showcase page records the download

- app/assets/javascripts/hyrax/ga_events.js
- app/helpers/morphosource/cart_item_helper.rb
- app/presenters/hyrax/work_usage.rb
- app/views/_ga.html.erb
- app/views/hyrax/stats/work.html.erb
- config/initializers/hyrax.rb
- spec/helpers/morphosource/cart_item_helper_spec.rb
- This ticket was prompted by User Stats for views and downloads not showing up. After investigation, it turns out that this doesn't happen automatically. If we want to get this going, we would need to set up a task to regularly match up google analytics data (page views and downloads by work) with the user who owns those works. 
- Updated ga_events.js to send work ids  instead of fileset ids for downloads to Google Analytics, and modified the Work stats related files to also include stats for downloads. This all seems to be working now, and stats can be viewed for a work by going to http://localhost:3000/works/WORK_ID/stats?locale=en
> MR-589: Investigate Why Download Stats Aren't Working

- .travis.yml
Current Travis "trusty" dist only has Python 3.4 as its Python 3, and installing a higher version is obnoxious. So for now we are sticking with Python 2 in Travis (Python 3 in Vagrant and Ansible Environments).
> Install Alembic dependencies in Travis and add Python environment variable

- .gitignore
- app/models/collection.rb
- config/initializers/morphosource/collection_form.rb
- config/initializers/morphosource/nested_collection_query_service.rb
- config/initializers/morphosource/nested_collections_search_builder.rb
- config/initializers/morphosource/permissions_create_service.rb
- lib/morphosource/collection_types/projects.rb
- lib/morphosource/collection_types/teams.rb
- lib/tasks/morphosource.rake
- spec/config/collection_form_spec.rb
- spec/config/nested_collection_query_service_spec.rb
- spec/config/nested_collections_search_builder_spec.rb
- spec/config/permissions_create_service_spec.rb
- spec/lib/morphosource/collections/projects_spec.rb
- spec/lib/morphosource/collections/teams_spec.rb
- spec/models/collection_spec.rb
- spec/tasks/morphosource_spec.rb
- Establishes Settings for Project and Team Collection Types
- Creates a rake task for setting up Team and Project Collection Types (morphosource:create_collection_types)
- Creates Manager/Depositor/Viewer groups upon Project or Team creation
- Assigns those groups to appropriate access grants
- Allows Projects to be nested within Teams
- Returns results for both projects and teams (when appropriate) when a user wants to select a collection to associate with another
> MR-620, MR-621: Create Team and Project Collection Types

- app/models/collection.rb
- spec/models/collection_spec.rb
- Hyrax already removes access grants & permission template when the collection is deleted.
> MR-626: Deleting a Team or Project also deletes its default user groups

- app/controllers/morphosource/dashboard/linked_teams_controller.rb
- app/helpers/morphosource/linked_teams_helper.rb
- app/models/collection.rb
- app/models/concerns/morphosource/organization_metadata.rb
- app/models/organization.rb
- app/presenters/hyrax/organization_presenter.rb
- app/views/hyrax/dashboard/collections/_ms_linked_organization.html.erb
- app/views/hyrax/dashboard/collections/show.html.erb
- config/initializers/morphosource/collection_presenter.rb
- config/routes.rb
- lib/morphosource/works/base.rb
- spec/controllers/morphosource/dashboard/linked_teams_controller_spec.rb
- spec/helpers/morphosource/collection_roles_helper_spec.rb
- spec/helpers/morphosource/linked_teams_helper_spec.rb
- spec/lib/morphosource/works/base_spec.rb
- spec/models/collection_spec.rb
- spec/models/organization_spec.rb
- spec/routing/linked_teams_routing_spec.rb
- Admins now have access to a select box on the dashboard collection page for teams that selects an organization to link to the team.
- Select only shows organizations not currently linked to a team.
- When an organization is linked, its metadata is displayed on the dashboard collection page, as well as stats for total number of specimens and media belonging and not belonging to the team.
- Adds a method to Morphosource::Works::Base for recursively getting all descendant works/filesets for a work
> MR-656: Link teams and organizations

- app/controllers/morphosource/dashboard/linked_teams_controller.rb
- spec/controllers/morphosource/dashboard/linked_teams_controller_spec.rb
When an organization is linked to a team, all child media of that organization that are not members of the team collection have the team's groups (manager, depositor, viewer) added to the media's read_users. This process is reversed if the organization is unlinked from the team.
> MR-671: Org-linked teams gain view access for org-associated media not managed by the team

- app/views/submissions/_biospec_search_results.html.erb
This fixes a small bug where any specimens with empty taxonomies cause search results to error.
> MR-90: fix bug for cases of empty taxonomies

- app/controllers/submissions_controller.rb
- app/models/submission.rb
This also fixes two bugs with reusing existing taxonomies for IDigBio results.
> MR-676: use IDigBio results as the canonical taxonomy
